const assert = require('assert');
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const source = fs.readFileSync(path.join(__dirname, 'app.js'), 'utf8');
const html = fs.readFileSync(path.join(__dirname, 'index.html'), 'utf8');
const css = fs.readFileSync(path.join(__dirname, 'style.css'), 'utf8');
const deploy = html.slice(html.indexOf('id="tab-deploy"'), html.indexOf('id="tab-files"'));
assert(deploy.indexOf('id="remediateCard"') < deploy.indexOf('id="deployHist"'), 'fixes precede history and build output');
assert(deploy.indexOf('id="remediateCard"') < deploy.indexOf('deploy-source-grid'), 'fixes are not buried below automation');
assert.equal((html.match(/id="remediateCard"/g) || []).length, 1);
assert(deploy.includes('class="deploy-log-card"') || deploy.includes('class="card deploy-log-card"'));
assert(/\.deploy-build-log\s*\{[^}]*height: 300px;[^}]*overflow: auto/s.test(css));
assert(/\.deploy-history\s*\{[^}]*max-height: 330px;[^}]*overflow: auto/s.test(css));
assert(css.includes('@media (max-width: 1050px)') && css.includes('grid-template-columns: minmax(0, 1fr)'));
assert(css.includes('#deployTail { max-height: 160px;'));
assert(/\.upgrade-log\s*\{[^}]*height: 360px;[^}]*overflow: auto/s.test(css));
const section = (start, end) => source.slice(source.indexOf(start), source.indexOf(end, source.indexOf(start)));
const context = vm.createContext({ safeHtml: text => String(text).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;') });
vm.runInContext(section('function deploySourceName(', 'let remediateSeq ='), context);
context.error = 'compiler cause <unsafe>\n' + 'full diagnostic\n'.repeat(1000);
const history = vm.runInContext('deployHistoryMarkup([{at:"2026-10-09",status:"error",error}])', context);
assert(history.includes('<details class="deploy-history-failure"') && !history.includes('<details class="deploy-history-failure" open'), 'long failures start collapsed');
assert(history.includes('full diagnostic\n'.repeat(1000).trim()) && history.includes('&lt;unsafe&gt;'), 'collapsing never removes full diagnostic evidence');
let writes = 0;
const detail = { open: true, dataset: { record: 'attempt' } };
const box = { dataset: {}, scrollTop: 100, querySelectorAll: query => query.includes('[open]') ? [detail] : [detail],
  get innerHTML() { return this.html; }, set innerHTML(value) { writes++; this.html = value; this.scrollTop = 0; detail.open = false; } };
context.box = box;
vm.runInContext('renderDeployMarkup(box, "rows"); renderDeployMarkup(box, "rows")', context);
assert.equal(writes, 1, 'identical status polls do not reset details or scroll');
assert.equal(box.scrollTop, 100);
assert(detail.open, 'expanded failure is retained after changed history');
console.log('Deploy layout: fixes first, independent bounded logs/history, collapsed full errors, responsive grids and stable scroll/details: OK');
