const assert = require('assert');
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const source = fs.readFileSync(path.join(__dirname, 'app.js'), 'utf8');
const elements = new Map();
const element = id => { if (!elements.has(id)) elements.set(id, { value: '', textContent: '', innerHTML: '', style: {}, title: '' }); return elements.get(id); };
const context = vm.createContext({ document: { getElementById: element, querySelector: () => ({ value: 'static' }), querySelectorAll: () => [] }, toast: () => {}, safeHtml: s => String(s).replace(/</g, '&lt;'), refresh: () => {}, closeCreate: () => {}, accessChanged: () => {} });
const section = (start, end) => source.slice(source.indexOf(start), source.indexOf(end, source.indexOf(start)));
vm.runInContext('let createModalSession=1, createDetectRequest=0, createConnectRequest=0, createDetectRepo="", createStandardDockerfile=false, createStorageAvailable=null, modalLogin=null, createCleanupPromise=Promise.resolve();\n' + section('function storageSize(', 'function storageMarkup(') + section('function setCreateStorage(', 'function resetCreateForm(') + section('function resetCreateForm(', 'function useCreateStandardDockerfile(') + section('async function createApp(', 'async function detectType(') + section('async function detectType(', 'function setSubdir('), context);
const run = code => vm.runInContext(code, context);
async function main() {
  run('resetCreateForm()');
  assert.equal(element('createStorageGB').value, '5');
  run('setCreateStorage(20)');
  assert.equal(element('createStorageGB').value, '20');
  element('createStorageGB').value = '7.125';
  element('name').value = 'demo';
  let saved;
  context.fetch = async (url, opts) => { saved = JSON.parse(opts.body); return { json: async () => ({ error: 'simulated create failure' }) }; };
  await run('createApp()');
  assert.equal(saved.storageGB, '7.125', 'custom size is sent without truncating/rounding to a preset');
  saved = null;
  element('createStorageGB').value = '-1';
  await run('createApp()');
  assert.equal(saved, null, 'invalid storage allowance is rejected before API call');
  context.fetch = async () => ({ json: async () => ({ ready: true, availableBytes: 8e9 }) });
  await run('loadCreateStorage()');
  run('setCreateStorage(200)');
  assert(element('createStorageHint').textContent.includes('exceeds'));
  element('createStorageGB').value = '3.5';
  run('updateCreateStorageHint()');
  assert.equal(element('createStorageHint').textContent, '');
  element('repo').value = 'https://github.com/owner/repo';
  context.fetch = async () => ({ json: async () => ({ type: 'static', branch: 'main', repositorySize: { bytes: 1048576, complete: true } }) });
  await run('detectType()');
  assert(element('createRepoSize').textContent.includes('approximately 1.0 MiB'));
  assert(element('createRepoSize').textContent.includes('database growth'));
  context.fetch = async () => ({ json: async () => ({ repositorySize: { bytes: 1048576, complete: false } }) });
  await run('detectType()');
  assert(element('createRepoSize').textContent.includes('at least'));
  let finish;
  context.fetch = () => new Promise(resolve => { finish = resolve; });
  const pending = run('loadCreateStorage()');
  run('resetCreateForm()');
  finish({ json: async () => ({ ready: true, availableBytes: 1e12 }) });
  await pending;
  assert.equal(element('createStorageState').textContent, 'Checking host quota setup…', 'previous modal quota responses are ignored');
  assert.equal(element('createStorageGB').value, '5');
  assert(element('createRepoSize').textContent.includes('choose'));
  console.log('Storage create UI: manual GB sizes, presets, capacity hints, branch-source estimates and stale/reset guards: OK');
}
main().catch(e => { console.error(e); process.exitCode = 1; });
