const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
process.env.DATA_FILE = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'minipass-panel-log-')), 'data.json');
const log = require('./panel-log');
assert(log.redact('see x-access-token:abc123@github.com/x').includes('x-access-token:***@'));
assert(!log.redact('see x-access-token:abc123@github.com/x').includes('abc123'));
assert(log.redact('DB_PASSWORD=hunter2 ok').includes('***') && !log.redact('DB_PASSWORD=hunter2 ok').includes('hunter2'));
assert(log.redact('plain message').includes('plain message'));
log.logEvent({ level: 'warn', area: 'create', site: 'demo', message: 'quota not enforced' });
log.logEvent({ area: 'trash', site: 'demo', message: 'cleanup failed' });
fs.appendFileSync(log.logPath(), 'not-json\n');
let events = log.readEvents(10);
assert.equal(events.length, 2, 'corrupt lines are skipped, newest first');
assert.equal(events[0].area, 'trash');
assert.equal(events[1].level, 'warn');
assert.deepEqual(log.readEvents(1).length, 1);
assert.deepEqual(log.readEvents(99999).length, 2, 'limit is clamped');
for (let i = 0; i < 3000; i++) log.logEvent({ area: 'fill', message: 'x'.repeat(200) });
events = log.readEvents(500);
assert(events.length <= 500 && events.length > 0, 'log rotates under the cap');
assert(fs.statSync(log.logPath()).size <= 512 * 1024 + 4096);
console.log('Panel error log: redaction, newest-first reads, corrupt-line tolerance and rotation: OK');
